name: Build & Deploy Image

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check:
    name: Build and Test Code
    runs-on: ubuntu-latest

    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18.3'
          cache: true
      - name: Install dependencies
        run: go get .
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test

  build-image:
    name: Bake and Validate Images
    needs: check
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

#      - name: Login to Container Reg
#        uses: docker/login-action@v1
#        with:
#          username: ${{ secrets.???_USERNAME }}
#          password: ${{ secrets.???_TOKEN }}

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v4
        with:
          images: devprodeng/wind-demo-go
          flavor: |
            latest=true
          tags: |
            type=ref,event=pr
            type=ref,event=branch

      - name: Build and export to Docker
        uses: docker/build-push-action@v3
        with:
          load: true # Export to Docker Engine rather than pushing to a registry
          tags: ${{ github.run_id }}
          #target: test
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run Trivy for all CVEs (non-blocking)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ github.run_id }}
          exit-code: 0
          format: table

      - name: Docker push
        uses: docker/build-push-action@v3
        with:
          push: false  #${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64
